export { default as Dashboard } from "./Dashboard";
export { default as Products } from "./Products";
export { default as Categories } from "./Categories";
export { default as Orders } from "./Orders";
export { default as Customers } from "./Customers";
export { default as LoginPage } from "./LoginPage";
export { default as NotFound } from "./NotFound";
export { default as Promotions } from "./Promotions";
export { default as ColorAndSize } from "./ColorAndSize";
